text = "I Love Georgia Very Much!!! XOXO"
print(text.capitalize())
print(text.casefold())
print(text.center(100))
print(text.count("X"))
print(text.encode())
print(text.endswith("XOXO"))
print(text.expandtabs())
print(text.find("Georgia"))
print(text.format())
mapping = {"country": "Georgia"}
print("I love {country}!".format_map(mapping))
print(text.index("Georgia"))
print(text.isalnum())
print(text.isalpha())
print(text.isascii())
print(text.isdecimal())
print(text.isdigit())
print(text.isidentifier())
print(text.islower())
print(text.isnumeric())
print(text.isprintable())
print(text.isspace())
print(text.istitle())
print(text.isupper())
print("-".join(text.split()))
print(text.ljust(50))
print(text.lower())
print(text.lstrip())
translation_table = str.maketrans("Georgia", "USA....")
print(text.translate(translation_table))
print(text.partition("Georgia"))
print(text.replace("Georgia", "USA"))
print(text.rfind("Very"))
print(text.rindex("Very"))
print(text.rjust(50))
print(text.rpartition("Very"))
print(text.rsplit())
print(text.rstrip())
print(text.split())
print(text.splitlines())
print(text.startswith("I Love"))
print(text.strip())
print(text.swapcase())
print(text.title())
print(text.upper())
print(text.zfill(50))